DROP TABLE Cfg.Members;
DROP TABLE Cfg.Visits;
DROP TABLE Cfg.Reports;
DROP TABLE Cfg.Installations;
DROP TABLE Cfg.Cities;
Go

CREATE SCHEMA Cfg;
go

CREATE FUNCTION [Int].[NewId]
(
  @i INT,
  @j INT
)
RETURNS INT

AS

BEGIN

  RETURN FLOOR(@i + RAND()*(@j-@i));

END
GO

CREATE TABLE Cfg.Cities (
    Id INT NOT NULL,
    [Name] NVARCHAR(50) NULL
);

ALTER TABLE Cfg.Cities ADD CONSTRAINT [Cfg.Cities.Pk.Id] PRIMARY KEY CLUSTERED(Id) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO

CREATE TABLE Cfg.Installations (
    Id INT NOT NULL,
    CityId INT NOT NULL,
    [Name] NVARCHAR(MAX) NULL
);

ALTER TABLE Cfg.Installations ADD CONSTRAINT [Cfg.Installations.Pk.Id] PRIMARY KEY CLUSTERED(Id) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE Cfg.Installations ADD CONSTRAINT [Cfg.Installations.Fk.CitiesId_Cfg.Cities.Id] FOREIGN KEY (CityId) REFERENCES Cfg.Cities(Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

CREATE TABLE Cfg.Reports (
    Id INT NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Surname VARCHAR(50) NOT NULL,
    Address VARCHAR(50) NULL,
    CityId INT NULL,
    InId INT NULL,
    Need TINYINT NULL,
    Active BIT NULL,
    Details NVARCHAR(MAX)
);

ALTER TABLE Cfg.Reports ADD CONSTRAINT [Cfg.Reports.Pk.Id] PRIMARY KEY CLUSTERED(Id) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE Cfg.Reports ADD CONSTRAINT [Cfg.Reports.Fk.CityId_Cfg.Cities.Id] FOREIGN KEY (CityId) REFERENCES Cfg.Cities(Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
ALTER TABLE Cfg.Reports ADD CONSTRAINT [Cfg.Reports.Fk.InId_Cfg.Installations.Id] FOREIGN KEY (InId) REFERENCES Cfg.Installations(Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

CREATE TABLE Cfg.Members (
    Id INT NOT NULL,
    Connector INT NOT NULL,
    [Member] VARCHAR(50) NULL,
    [Name] VARCHAR(50) NULL,
    YearOfBirth INT NULL,
    Age SMALLINT NULL,
    Details NVARCHAR(MAX) NULL
);

ALTER TABLE Cfg.Members ADD CONSTRAINT [Cfg.Members.Pk.Id] PRIMARY KEY CLUSTERED(Id) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE Cfg.Members ADD CONSTRAINT [Cfg.Members.Fk.Connector_Cfg.Reports.Id] FOREIGN KEY (Connector) REFERENCES Cfg.Reports(Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

CREATE TABLE Cfg.Visits (
    Id INT NOT NULL,
    Connector INT NOT NULL,
    InIdOwner INT NOT NULL,
    InIdVisitor INT NOT NULL,
    VisitorName NVARCHAR(MAX) NULL,
    Details NVARCHAR(MAX) NULL,
    DateOfVisit DATE NULL
);

ALTER TABLE Cfg.Visits ADD CONSTRAINT [Cfg.Visits.Pk.Id] PRIMARY KEY CLUSTERED(Id) WITH(STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO
ALTER TABLE Cfg.Visits ADD CONSTRAINT [Cfg.Visits.Fk.Connector_Cfg.Reports.Id] FOREIGN KEY (Connector) REFERENCES Cfg.Reports(Id) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

